version: '3.8'

services:
  # Ultra-fast development service
  dev-fast:
    build: 
      context: .
      dockerfile: Dockerfile.dev.fast
    container_name: aken-reporting-service-dev-fast
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - ENV=development
      - DISABLE_AUTH=true
      - GIN_MODE=debug
      # Database connection
      - PMT_TX_DB_HOST=postgres
      - PMT_TX_DB_PORT=5432
      - PMT_TX_DB_USER=wizzit_pay
      - PMT_TX_DB_PASSWORD=wizzit_pay
      - PMT_TX_DB_DATABASE=wizzit_pay
      # Redis configuration
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_POOL_SIZE=10
      - REDIS_TIMEOUT=5
      - REDIS_TTL_SECONDS=1800
      - REDIS_KEY_PREFIX=aken:reporting
    depends_on:
      - postgres
      - redis
    networks:
      - aken-network

  # PostgreSQL database
  postgres:
    image: postgres:13
    container_name: aken-postgres
    environment:
      - POSTGRES_DB=wizzit_pay
      - POSTGRES_USER=wizzit_pay
      - POSTGRES_PASSWORD=wizzit_pay
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - aken-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: aken-redis
    ports:
      - "6379:6379"
    networks:
      - aken-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  aken-network:
    driver: bridge