version: '3.8'

services:
  # Development service (for make dev)
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: aken-reporting-service-dev
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - ENV=development
      - DISABLE_AUTH=false
      - GIN_MODE=debug
      # Database connection
      - PMT_TX_DB_HOST=postgres
      - PMT_TX_DB_PORT=5432
      - PMT_TX_DB_USER=wizzit_pay
      - PMT_TX_DB_PASSWORD=wizzit_pay
      - PMT_TX_DB_DATABASE=wizzit_pay
      # Redis configuration
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_POOL_SIZE=10
      - REDIS_TIMEOUT=5
      - REDIS_TTL_SECONDS=1800
      - REDIS_KEY_PREFIX=aken:reporting
    depends_on:
      - postgres
      - redis
    networks:
      - aken-network

  # Production service (for make build)
  prod:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aken-reporting-service
    image: aken-reporting-service
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - aken-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/v2/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Main service (backwards compatibility)
  aken-reporting-service:
    build: .
    container_name: aken-reporting-service
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - ENV=development
      - DISABLE_AUTH=false
      # Database connection (connects to existing AKEN database)
      - PMT_TX_DB_HOST=postgres
      - PMT_TX_DB_PORT=5432
      - PMT_TX_DB_USER=wizzit_pay
      - PMT_TX_DB_PASSWORD=wizzit_pay
      - PMT_TX_DB_DATABASE=wizzit_pay
      # Redis configuration
      - REDIS_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD
      - REDIS_DB=0
      - REDIS_POOL_SIZE=10
      - REDIS_TIMEOUT=5
      - REDIS_TTL_SECONDS=1800
      - REDIS_KEY_PREFIX=aken:reporting
    depends_on:
      - postgres
    networks:
      - aken-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/v2/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL database (shared with main AKEN service)
  postgres:
    image: postgres:13
    container_name: aken-postgres
    environment:
      - POSTGRES_DB=wizzit_pay
      - POSTGRES_USER=wizzit_pay
      - POSTGRES_PASSWORD=wizzit_pay
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - aken-network
    restart: unless-stopped

  # Redis for future caching (optional)
  redis:
    image: redis:7-alpine
    container_name: aken-redis
    ports:
      - "6379:6379"
    networks:
      - aken-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  aken-network:
    driver: bridge